<?php

namespace App\Http\Controllers;

use App\Models\UploadedFile;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * §23: "download authorization". Even a signed URL (which proves the link
 * itself wasn't tampered with and hasn't expired) is checked AGAIN here
 * against the requesting user's tenant and permissions — a signed link
 * that leaked doesn't bypass authorization, it only proves the link was
 * generated by this app for someone who, at generation time, could see
 * the file. Every successful download is also an Auditable write via
 * UploadedFile's own trail of who uploaded it; the download itself isn't
 * separately logged here to avoid flooding audit_logs with routine image
 * views — revisit if that granularity turns out to matter.
 */
class FileDownloadController extends Controller
{
    public function show(Request $request, UploadedFile $uploadedFile): StreamedResponse
    {
        abort_unless($request->hasValidSignature(), 403, 'This download link is invalid or has expired.');
        abort_unless($uploadedFile->church_id === $request->user()->church_id, 403);

        abort_unless(Storage::disk('private')->exists($uploadedFile->disk_path), 404);

        return Storage::disk('private')->response(
            $uploadedFile->disk_path,
            $uploadedFile->original_filename,
            ['Content-Type' => $uploadedFile->mime_type],
        );
    }
}
